// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/rpc/protobuf/rpc.proto

package rpc.protobuf;

public final class RPCProtocol {
  private RPCProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RPCCallOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string classname = 1;
    boolean hasClassname();
    String getClassname();
    
    // required string methodname = 2;
    boolean hasMethodname();
    String getMethodname();
    
    // repeated bytes parameters = 3;
    java.util.List<com.google.protobuf.ByteString> getParametersList();
    int getParametersCount();
    com.google.protobuf.ByteString getParameters(int index);
  }
  public static final class RPCCall extends
      com.google.protobuf.GeneratedMessage
      implements RPCCallOrBuilder {
    // Use RPCCall.newBuilder() to construct.
    private RPCCall(Builder builder) {
      super(builder);
    }
    private RPCCall(boolean noInit) {}
    
    private static final RPCCall defaultInstance;
    public static RPCCall getDefaultInstance() {
      return defaultInstance;
    }
    
    public RPCCall getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rpc.protobuf.RPCProtocol.internal_static_rpc_protobuf_RPCCall_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rpc.protobuf.RPCProtocol.internal_static_rpc_protobuf_RPCCall_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string classname = 1;
    public static final int CLASSNAME_FIELD_NUMBER = 1;
    private java.lang.Object classname_;
    public boolean hasClassname() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getClassname() {
      java.lang.Object ref = classname_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          classname_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getClassnameBytes() {
      java.lang.Object ref = classname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        classname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string methodname = 2;
    public static final int METHODNAME_FIELD_NUMBER = 2;
    private java.lang.Object methodname_;
    public boolean hasMethodname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getMethodname() {
      java.lang.Object ref = methodname_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          methodname_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMethodnameBytes() {
      java.lang.Object ref = methodname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        methodname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated bytes parameters = 3;
    public static final int PARAMETERS_FIELD_NUMBER = 3;
    private java.util.List<com.google.protobuf.ByteString> parameters_;
    public java.util.List<com.google.protobuf.ByteString>
        getParametersList() {
      return parameters_;
    }
    public int getParametersCount() {
      return parameters_.size();
    }
    public com.google.protobuf.ByteString getParameters(int index) {
      return parameters_.get(index);
    }
    
    private void initFields() {
      classname_ = "";
      methodname_ = "";
      parameters_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasClassname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMethodname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getClassnameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getMethodnameBytes());
      }
      for (int i = 0; i < parameters_.size(); i++) {
        output.writeBytes(3, parameters_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getClassnameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMethodnameBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < parameters_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(parameters_.get(i));
        }
        size += dataSize;
        size += 1 * getParametersList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rpc.protobuf.RPCProtocol.RPCCall parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rpc.protobuf.RPCProtocol.RPCCall parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rpc.protobuf.RPCProtocol.RPCCall parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rpc.protobuf.RPCProtocol.RPCCall parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rpc.protobuf.RPCProtocol.RPCCall parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rpc.protobuf.RPCProtocol.RPCCall parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rpc.protobuf.RPCProtocol.RPCCall parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rpc.protobuf.RPCProtocol.RPCCall parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rpc.protobuf.RPCProtocol.RPCCall parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rpc.protobuf.RPCProtocol.RPCCall parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rpc.protobuf.RPCProtocol.RPCCall prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rpc.protobuf.RPCProtocol.RPCCallOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rpc.protobuf.RPCProtocol.internal_static_rpc_protobuf_RPCCall_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rpc.protobuf.RPCProtocol.internal_static_rpc_protobuf_RPCCall_fieldAccessorTable;
      }
      
      // Construct using rpc.protobuf.RPCProtocol.RPCCall.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        classname_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        methodname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        parameters_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rpc.protobuf.RPCProtocol.RPCCall.getDescriptor();
      }
      
      public rpc.protobuf.RPCProtocol.RPCCall getDefaultInstanceForType() {
        return rpc.protobuf.RPCProtocol.RPCCall.getDefaultInstance();
      }
      
      public rpc.protobuf.RPCProtocol.RPCCall build() {
        rpc.protobuf.RPCProtocol.RPCCall result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rpc.protobuf.RPCProtocol.RPCCall buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rpc.protobuf.RPCProtocol.RPCCall result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rpc.protobuf.RPCProtocol.RPCCall buildPartial() {
        rpc.protobuf.RPCProtocol.RPCCall result = new rpc.protobuf.RPCProtocol.RPCCall(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.classname_ = classname_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.methodname_ = methodname_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          parameters_ = java.util.Collections.unmodifiableList(parameters_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.parameters_ = parameters_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rpc.protobuf.RPCProtocol.RPCCall) {
          return mergeFrom((rpc.protobuf.RPCProtocol.RPCCall)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rpc.protobuf.RPCProtocol.RPCCall other) {
        if (other == rpc.protobuf.RPCProtocol.RPCCall.getDefaultInstance()) return this;
        if (other.hasClassname()) {
          setClassname(other.getClassname());
        }
        if (other.hasMethodname()) {
          setMethodname(other.getMethodname());
        }
        if (!other.parameters_.isEmpty()) {
          if (parameters_.isEmpty()) {
            parameters_ = other.parameters_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureParametersIsMutable();
            parameters_.addAll(other.parameters_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasClassname()) {
          
          return false;
        }
        if (!hasMethodname()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              classname_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              methodname_ = input.readBytes();
              break;
            }
            case 26: {
              ensureParametersIsMutable();
              parameters_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string classname = 1;
      private java.lang.Object classname_ = "";
      public boolean hasClassname() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getClassname() {
        java.lang.Object ref = classname_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          classname_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setClassname(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        classname_ = value;
        onChanged();
        return this;
      }
      public Builder clearClassname() {
        bitField0_ = (bitField0_ & ~0x00000001);
        classname_ = getDefaultInstance().getClassname();
        onChanged();
        return this;
      }
      void setClassname(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        classname_ = value;
        onChanged();
      }
      
      // required string methodname = 2;
      private java.lang.Object methodname_ = "";
      public boolean hasMethodname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getMethodname() {
        java.lang.Object ref = methodname_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          methodname_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMethodname(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        methodname_ = value;
        onChanged();
        return this;
      }
      public Builder clearMethodname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        methodname_ = getDefaultInstance().getMethodname();
        onChanged();
        return this;
      }
      void setMethodname(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        methodname_ = value;
        onChanged();
      }
      
      // repeated bytes parameters = 3;
      private java.util.List<com.google.protobuf.ByteString> parameters_ = java.util.Collections.emptyList();;
      private void ensureParametersIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          parameters_ = new java.util.ArrayList<com.google.protobuf.ByteString>(parameters_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<com.google.protobuf.ByteString>
          getParametersList() {
        return java.util.Collections.unmodifiableList(parameters_);
      }
      public int getParametersCount() {
        return parameters_.size();
      }
      public com.google.protobuf.ByteString getParameters(int index) {
        return parameters_.get(index);
      }
      public Builder setParameters(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParametersIsMutable();
        parameters_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addParameters(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParametersIsMutable();
        parameters_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllParameters(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureParametersIsMutable();
        super.addAll(values, parameters_);
        onChanged();
        return this;
      }
      public Builder clearParameters() {
        parameters_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:rpc.protobuf.RPCCall)
    }
    
    static {
      defaultInstance = new RPCCall(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rpc.protobuf.RPCCall)
  }
  
  public interface RPCResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bytes result = 1;
    boolean hasResult();
    com.google.protobuf.ByteString getResult();
    
    // optional bytes exception = 2;
    boolean hasException();
    com.google.protobuf.ByteString getException();
  }
  public static final class RPCResult extends
      com.google.protobuf.GeneratedMessage
      implements RPCResultOrBuilder {
    // Use RPCResult.newBuilder() to construct.
    private RPCResult(Builder builder) {
      super(builder);
    }
    private RPCResult(boolean noInit) {}
    
    private static final RPCResult defaultInstance;
    public static RPCResult getDefaultInstance() {
      return defaultInstance;
    }
    
    public RPCResult getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rpc.protobuf.RPCProtocol.internal_static_rpc_protobuf_RPCResult_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rpc.protobuf.RPCProtocol.internal_static_rpc_protobuf_RPCResult_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bytes result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString result_;
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getResult() {
      return result_;
    }
    
    // optional bytes exception = 2;
    public static final int EXCEPTION_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString exception_;
    public boolean hasException() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getException() {
      return exception_;
    }
    
    private void initFields() {
      result_ = com.google.protobuf.ByteString.EMPTY;
      exception_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, exception_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, result_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, exception_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static rpc.protobuf.RPCProtocol.RPCResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rpc.protobuf.RPCProtocol.RPCResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rpc.protobuf.RPCProtocol.RPCResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rpc.protobuf.RPCProtocol.RPCResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rpc.protobuf.RPCProtocol.RPCResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rpc.protobuf.RPCProtocol.RPCResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rpc.protobuf.RPCProtocol.RPCResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rpc.protobuf.RPCProtocol.RPCResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rpc.protobuf.RPCProtocol.RPCResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rpc.protobuf.RPCProtocol.RPCResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rpc.protobuf.RPCProtocol.RPCResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements rpc.protobuf.RPCProtocol.RPCResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return rpc.protobuf.RPCProtocol.internal_static_rpc_protobuf_RPCResult_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return rpc.protobuf.RPCProtocol.internal_static_rpc_protobuf_RPCResult_fieldAccessorTable;
      }
      
      // Construct using rpc.protobuf.RPCProtocol.RPCResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        result_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        exception_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rpc.protobuf.RPCProtocol.RPCResult.getDescriptor();
      }
      
      public rpc.protobuf.RPCProtocol.RPCResult getDefaultInstanceForType() {
        return rpc.protobuf.RPCProtocol.RPCResult.getDefaultInstance();
      }
      
      public rpc.protobuf.RPCProtocol.RPCResult build() {
        rpc.protobuf.RPCProtocol.RPCResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private rpc.protobuf.RPCProtocol.RPCResult buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        rpc.protobuf.RPCProtocol.RPCResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public rpc.protobuf.RPCProtocol.RPCResult buildPartial() {
        rpc.protobuf.RPCProtocol.RPCResult result = new rpc.protobuf.RPCProtocol.RPCResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.exception_ = exception_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rpc.protobuf.RPCProtocol.RPCResult) {
          return mergeFrom((rpc.protobuf.RPCProtocol.RPCResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rpc.protobuf.RPCProtocol.RPCResult other) {
        if (other == rpc.protobuf.RPCProtocol.RPCResult.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasException()) {
          setException(other.getException());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              result_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              exception_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bytes result = 1;
      private com.google.protobuf.ByteString result_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getResult() {
        return result_;
      }
      public Builder setResult(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      
      // optional bytes exception = 2;
      private com.google.protobuf.ByteString exception_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasException() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getException() {
        return exception_;
      }
      public Builder setException(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        exception_ = value;
        onChanged();
        return this;
      }
      public Builder clearException() {
        bitField0_ = (bitField0_ & ~0x00000002);
        exception_ = getDefaultInstance().getException();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:rpc.protobuf.RPCResult)
    }
    
    static {
      defaultInstance = new RPCResult(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rpc.protobuf.RPCResult)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_protobuf_RPCCall_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rpc_protobuf_RPCCall_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_protobuf_RPCResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rpc_protobuf_RPCResult_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032src/rpc/protobuf/rpc.proto\022\014rpc.protob" +
      "uf\"D\n\007RPCCall\022\021\n\tclassname\030\001 \002(\t\022\022\n\nmeth" +
      "odname\030\002 \002(\t\022\022\n\nparameters\030\003 \003(\014\".\n\tRPCR" +
      "esult\022\016\n\006result\030\001 \001(\014\022\021\n\texception\030\002 \001(\014" +
      "B\033\n\014rpc.protobufB\013RPCProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rpc_protobuf_RPCCall_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rpc_protobuf_RPCCall_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rpc_protobuf_RPCCall_descriptor,
              new java.lang.String[] { "Classname", "Methodname", "Parameters", },
              rpc.protobuf.RPCProtocol.RPCCall.class,
              rpc.protobuf.RPCProtocol.RPCCall.Builder.class);
          internal_static_rpc_protobuf_RPCResult_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_rpc_protobuf_RPCResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rpc_protobuf_RPCResult_descriptor,
              new java.lang.String[] { "Result", "Exception", },
              rpc.protobuf.RPCProtocol.RPCResult.class,
              rpc.protobuf.RPCProtocol.RPCResult.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
